name: Generate index

on:
  push:
    branches: 'main'
    paths:
      - 'localized_data/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release
          fetch-depth: 0

      - name: Merge changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git merge -X theirs origin/main

      - uses: actions/setup-python@v5
        with:
            python-version: "3.12"

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Create index
        run: python gen_index.py

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update index
          branch: release
          file_pattern: 'index.json'